services:
  - type: web
    name: twilio-outbound-service
    env: python
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BASE_URL
        value: ""
      - key: CALL_PROVIDER
        value: "twilio"
    secrets: []
